# Adaptive extraction settings for document processing
# Minimum containers to find valid pattern
DEFAULT_MIN_CONTAINERS = 3
# Maximum DOM depth to analyze
DEFAULT_MAX_DEPTH = 20

# Minimum confidence score for extraction
DEFAULT_CONFIDENCE_THRESHOLD = 0.4

# Weights
TITLE_WEIGHT = 0.4
LINK_WEIGHT = 0.3
KICKER_WEIGHT = 0.15
IMAGE_WEIGHT = 0.15

CONTAINER_MIN_TEXT_LENGTH = 20
CONTAINER_MIN_DEPTH = 3

ELEMENT_GROUP_FACTOR = 10
SIBLING_GROUP_FACTOR = 5

MINIMUM_TITLE_LENGTH = 10
MINIMUM_KICKER_LENGTH = 11
MINIMUM_THRESHOLD_SCORE = 0.3

DEFAULT_IMAGE_SIZE_SCORE = 0.5
DEFAULT_LINK_SCORE = 0.5

MINIMUM_CHILD_TEXT_LENGTH = 10

DEFAULT_MODEL_NAME = "all-MiniLM-L6-v2"
